# Generated by Django 5.0.4 on 2024-04-09 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('607b7987-c632-4709-95c4-824176cf4991'), primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('encrypted_file_key', models.CharField(max_length=255)),
                ('encrypted_file_url', models.URLField(blank=True)),
            ],
        ),
    ]
