# Generated by Django 5.0.4 on 2024-04-09 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('705dbdd4-ca44-41de-935a-b69bd3efe28d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads\\'),
        ),
    ]
