# Generated by Django 5.0.4 on 2024-04-09 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_alter_encryptedfile_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a3e958b8-202f-439e-8eda-721db0dca0e5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
