# Generated by Django 5.0.4 on 2024-04-09 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0004_alter_encryptedfile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('cc2b621a-421f-4a17-82e6-5a154c0b52ae'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
