# Generated by Django 5.0.4 on 2024-04-09 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0005_alter_encryptedfile_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('437f11d9-3035-40dd-b046-51dd2d7155d2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads\\'),
        ),
    ]
