# Generated by Django 5.0.4 on 2024-04-10 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0007_alter_encryptedfile_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads\\'),
        ),
    ]
